import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/receipt.module.css";
import API from "../utils/api";
import useAPISWR from "../utils/swr";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Receipt</title>
        <meta name="description" content="Generated by receipt" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Get your QR code</h1>
      </main>
      <pre>{JSON.stringify(useAPISWR([API.getPing, {}]))}</pre>
    </div>
  );
};

export default Home;
