name: Tests

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm set-script postinstall ""
    - run: npm install
    - run: npx lerna bootstrap --no-ci
    - run: npm run compile
      working-directory: back
    - run: NODE_ENV=test npx lerna run types
    - run: NODE_ENV=test npx lerna run lint
    - run: NODE_ENV=test npx lerna run jest

